SELECT 
    (SELECT COUNT(*) FROM ORDERS WHERE EXTRACT(YEAR FROM ORDER_DATE) = 1996) AS ORDERS_IN_1996,
    (SELECT COUNT(*) FROM ORDERS WHERE EXTRACT(YEAR FROM ORDER_DATE) = 1997) AS ORDERS_IN_1997,
    ((SELECT COUNT(*) FROM ORDERS WHERE EXTRACT(YEAR FROM ORDER_DATE) = 1997) - 
    (SELECT COUNT(*) FROM ORDERS WHERE EXTRACT(YEAR FROM ORDER_DATE) = 1996)) AS DIFFERENCE;
